services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped
  # mongodb:
  #   image: mongo:7
  #   container_name: mongodb
  #   restart: unless-stopped
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: lsmarena
  #     MONGO_INITDB_ROOT_PASSWORD: admin123
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
  lsm-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: lsm-server:dev
    container_name: lsm-server
    ports:
      - 7777:7777
    depends_on: 
    - qdrant
    environment:
       QDRANT_HOST: qdrant
       QDRANT_PORT: 6333
       MONGO_HOST: mongodb
       MONGO_PORT: 27017
    restart: unless-stopped
    command: ["bash", "-c", "python3 qdrant_init.py && python3 lsm_server.py"]

volumes:
  qdrant_storage:
  mongo_data:
